"""
Pydantic schemas for the IBKR Alerts tool.
This module defines the validation models for request bodies and responses
as specified in the Interactive Brokers Client Portal API documentation.
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Union, Dict, Any

class AlertCondition(BaseModel):
    """
    Validation schema for an individual alert trigger condition.
    """
    type: int = Field(
        ..., 
        description=(
            "Condition type code: "
            "1: Price, 3: Time, 4: Margin, 5: Trade, 6: Volume, "
            "7: MTA market, 8: MTA Position, 9: MTA Account Daily PnL"
        )
    )
    conidex: Optional[str] = Field(
        None, 
        description="Concatenation of contract ID and exchange: 'conid@exchange' (e.g., '265598@SMART')"
    )
    operator: str = Field(
        ..., 
        description="Comparison operator for the trigger (e.g., '>=', '<=', '==')"
    )
    value: str = Field(
        ..., 
        description="The target value that triggers the condition"
    )
    logicBind: str = Field(
        "n", 
        description="Logical binder for multiple conditions: 'a' for AND, 'o' for OR, 'n' for END (last condition)"
    )
    triggerMethod: int = Field(
        0, 
        description="Trigger method for price-based conditions, usually 0 (default)"
    )
    timeZone: Optional[str] = Field(
        None, 
        description="Time zone for time-specific conditions (e.g., 'US/Eastern')"
    )

class AlertCreateRequest(BaseModel):
    """
    Validation schema for creating or modifying an IBKR alert.
    """
    alertName: str = Field(..., description="Human-readable identifier for the alert")
    alertMessage: str = Field(..., description="Message content to be sent when triggered")
    alertRepeatable: int = Field(
        0, ge=0, le=1, 
        description="Whether the alert persists after triggering: 0 for once, 1 for repeatable"
    )
    tif: str = Field(
        "GTC", 
        description="Time in Force: 'GTC' (Good Till Cancelled) or 'GTD' (Good Till Date)"
    )
    expireTime: Optional[str] = Field(
        None, 
        description="Required if tif is 'GTD'. Format: 'YYYYMMDD-HH:mm:ss'"
    )
    outsideRth: int = Field(
        0, ge=0, le=1, 
        description="Allow the alert to trigger outside regular trading hours (1 for yes, 0 for no)"
    )
    iTWSOrdersOnly: int = Field(
        0, ge=0, le=1, 
        description="Trigger notifications only through the IBKR mobile app (1 for yes, 0 for no)"
    )
    showPopup: int = Field(
        0, ge=0, le=1, 
        description="Display a popup notification in Trader Workstation (1 for yes, 0 for no)"
    )
    sendMessage: int = Field(
        1, ge=0, le=1, 
        description="Send an email or message notification (1 for yes, 0 for no)"
    )
    email: Optional[str] = Field(
        None, 
        description="The destination email address. Required if sendMessage is 1."
    )
    conditions: List[AlertCondition] = Field(
        ..., 
        description="List of trigger conditions attached to the alert."
    )

class AlertResponse(BaseModel):
    """
    Validation schema for a standard response from alert creation, modification, or deletion.
    """
    order_id: int = Field(..., description="Unique order/alert ID generated by IBKR")
    success: bool = Field(..., description="Indicates if the request was successful")
    text: Optional[str] = Field(None, description="Descriptive status message from the gateway")
    request_id: Optional[int] = Field(None, description="Optional request tracking ID")

class AlertListItem(BaseModel):
    """
    Validation schema for an alert summary item returned in a list operation.
    """
    order_id: int = Field(..., description="The unique alert ID")
    account: str = Field(..., description="The account ID the alert belongs to")
    alert_name: str = Field(..., description="The name of the alert")
    alert_active: int = Field(..., description="Current status: 1 for active, 0 for inactive")
    order_time: str = Field(..., description="Creation time of the alert")
    alert_triggered: bool = Field(..., description="Whether the alert has been triggered")
    alert_repeatable: int = Field(..., description="1 if repeatable, 0 otherwise")

class AlertDetails(BaseModel):
    """
    Validation schema for the complete details of a specific alert.
    """
    account: str = Field(..., description="Account ID")
    order_id: int = Field(..., description="The unique alert ID")
    alert_name: str = Field(..., description="Name of the alert")
    tif: str = Field(..., description="Time in Force settings")
    expire_time: Optional[str] = Field(None, description="Expiration time for GTD alerts")
    alert_active: int = Field(..., description="Status: 1 for active, 0 for inactive")
    alert_repeatable: int = Field(..., description="Repeatable status")
    alert_email: Optional[str] = Field(None, description="Email address for notifications")
    alert_send_message: int = Field(..., description="Email notification status")
    alert_message: str = Field(..., description="The alert message body")
    alert_show_popup: int = Field(..., description="TWS popup status")
    alert_triggered: bool = Field(..., description="Trigger status")
    condition_size: int = Field(..., description="Total number of conditions")
    condition_outside_rth: int = Field(..., description="Outside RTH status")
    conditions: List[Dict[str, Any]] = Field(default=[], description="Detailed list of conditions")
